# Generated by Django 2.2.11 on 2020-05-17 07:22

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200510_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='presences',
            name='date2',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=None),
        ),
    ]
